### PR TITLE
Fix issue #67 (various objects not callable)

### PR DESCRIPTION
**Pull request by WetDesertRock**
Either an API changed or this file was untested, but this fixes issue #67.
Various objects were getting used as getters when they were just the value.

I don't expect that this is a complete fix, however it runs this example program:

``` lua
local nw = require'nw'

local app = nw:app()        --get the app singleton

local win = app:window{     --create a new window
   w = 400, h = 200,        --specify window's frame size
   title = 'hello',         --specify window's title
   visible = false,         --don't show it yet
}

function win:click(button, count) --this is one way to bind events
   if button == 'left' and count == 3 then --triple click
      app:quit()
   end
end

--this is another way to bind events which allows setting multiple
--handlers for the same event type.
win:on('keydown', function(self, key)
   if key == 'F11' then
      self:fullscreen(not self:fullscreen()) --toggle fullscreen state
   end
end)

function win:repaint()        --called when window needs repainting
   local bmp = win:bitmap()   --get the window's bitmap
   local cr = bmp:cairo()     --get a cairo drawing context
   cr:rgb(0, 1, 0)            --make it green
   cr:paint()
end

win:show() --show it now that it was properly set up

app:run()  --start the event loop
```

### CODE REVIEW

**Comment by capr** [comment]
That file was tested. It seems that the problem is either with the `objc` module or with your particular version of OSX, which doesn't publish the metadata for properties so that you can access them with the dot notation. Which OSX are you running?

**Comment by WetDesertRock** [comment]
I am using OSX 10.10.5

**Comment by capr** [comment]
Objc was only tested with 10.9 (see https://luapower.com/objc). I think it might need fixing for 10.10. Can you run the objc tests and demos and try to figure out where the problem is?

**Comment by WetDesertRock** [comment]
I ran as many as I could, included are the ones that failed. Only one failing without the `x is not callable` message was http_gcd which ended with an `Abort trap: 6`

## Demos:
### http
`luapower/bin/osx64/luajit-bin: objc_test.lua:567: 'uint64_t' is not callable
stack traceback:
	[C]: in function 'length'
	objc_test.lua:567: in function 'test'
	objc_test.lua:852: in function 'run'
	objc_test.lua:857: in main chunk
	[C]: at 0x0100000b90`
  
### http_gcd
`[objc] block            create	refcount: 1       
[objc] block            copy	refcount: 2       
[objc] block            copy	refcount: 3       
queued
[objc] block            dispose	refcount: 2       
released
called	1
libc++abi.dylib: terminating with uncaught foreign exception
Abort trap: 6`

## Eye Tests
Skipped most because I don't have the Java 6 runtime (I do have later Java's installed though)

Indent, and tostring did pass though

## Tests
### args
`luapower/bin/osx64/luajit-bin: objc_test.lua:494: attempt to call method 'doubleValue' (a number value)
stack traceback:
	objc_test.lua:494: in function 'test'
	objc_test.lua:852: in function 'run'
	objc_test.lua:857: in main chunk
	[C]: at 0x0100000b90`
  
### override
`[objc] addmethod          MyClass1                                 description                              class    id (*) (id, SEL)
[objc] addmethod          MyClass1                                 description                              inst     id (*) (id, SEL)
luapower/bin/osx64/luajit-bin: objc_test.lua:337: 'struct objc_object' is not callable
stack traceback:
	[C]: in function 'description'
	objc_test.lua:337: in function 'test'
	objc_test.lua:852: in function 'run'
	objc_test.lua:857: in main chunk
	[C]: at 0x0100000b90`

### tolua
`luapower/bin/osx64/luajit-bin: ./objc.lua:2102: attempt to call method 'doubleValue' (a number value)
stack traceback:
	./objc.lua:2102: in function 'tolua'
	objc_test.lua:453: in function 'test'
	objc_test.lua:852: in function 'run'
	objc_test.lua:857: in main chunk
	[C]: at 0x0100000b90`

**Comment by Robert-M-Muench** [comment]
I just made some of the same changes (set / getter changed to values) before seeing this here... I'm on 10.10 as well.

**Pull request closed without merging**
